package main

import (
	"context"
	_ "embed"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/qiangli/yoke/external/zigcc"
)

// fnmatchCompatHeader is a self-contained POSIX fnmatch(3) (musl's, MIT; see
// the file's own banner). The GNU glob-bracket fixture compiles and runs a tiny
// fnmatch program via $CC; the mingw / zig cc windows-gnu target ships no
// <fnmatch.h>, so that compile fails and the fixture aborts before printing a
// line. Injecting this header with -isystem lets the compile resolve and the
// program run — byte-identical to the fixture's recorded fnmatch column.
//
//go:embed compat/fnmatch.h
var fnmatchCompatHeader []byte

// strmatchStubSource defines the one symbol the glob-bracket strmatch loadable
// leaves undefined. On a real bash the loader resolves `strmatch` from bash's
// own exported symbol table at dlopen time; bashy implements strmatch as an
// internal builtin instead and `enable -f` never loads the .so (it only checks
// the file exists). But the fixture still LINKS strmatch.so, and a Windows
// shared object cannot carry an unresolved import, so the link would fail and
// the file would never appear. This stub gives the link a definition so the
// marker file is produced; its contents are irrelevant on every platform,
// exactly as the never-loaded .so is on the canonical hosts.
const strmatchStubSource = `/* generated by tools/bash53suite: satisfies the glob-bracket strmatch.so
   link on a Windows target, where a shared object may carry no unresolved
   import. The .so is never loaded — bashy's strmatch is an internal builtin —
   so this definition only lets the marker file be produced. */
int strmatch(char *pattern, char *string, int flags) {
	(void)pattern;
	(void)string;
	(void)flags;
	return 0;
}
`

// ccLauncherSource is a tiny `cc` the fixtures find on PATH. zig exposes its C
// frontend as a subcommand (`zig cc`), which is two words, and it also needs
// the target triple and the compat include dir; a bare name on PATH cannot be
// two words. This launcher is a real PE (CreateProcess runs it; a .cmd wrapper
// would not, because os/exec hands the batch file straight to CreateProcess),
// which prepends `cc -target … -isystem …` to zig and waits for it, returning
// zig's own exit status. The three %s are C string literals filled by
// writeCCLauncher with backslashes escaped.
const ccLauncherSource = `/* generated by tools/bash53suite: a PATH-resolvable cc that re-enters the
   provisioned zig toolchain with the fixture target and compat headers. */
#include <stdlib.h>
#include <process.h>
#define ZIG "%s"
#define TARGET "%s"
#define COMPAT "%s"
int main(int argc, char **argv) {
	const char *pre[] = { ZIG, "cc", "-target", TARGET, "-isystem", COMPAT };
	int npre = (int)(sizeof(pre) / sizeof(pre[0]));
	const char **av = (const char **)malloc(sizeof(char *) * (npre + argc));
	if (!av) return 127;
	int j = 0;
	for (int i = 0; i < npre; i++) av[j++] = pre[i];
	for (int i = 1; i < argc; i++) av[j++] = argv[i];
	av[j] = 0;
	intptr_t rc = _spawnv(_P_WAIT, ZIG, (const char *const *)av);
	free(av);
	return rc < 0 ? 127 : (int)rc;
}
`

// windowsFixtureCC is the result of provisioning a POSIX-behaving C compiler
// for the Windows fixture runner.
type windowsFixtureCC struct {
	// Dir holds the `cc` launcher and is prepended to the fixture PATH.
	Dir string
	// StubObject is the compiled strmatch stub, handed to the generated
	// examples/loadables/Makefile as SHOBJ_LIBS so strmatch.so links.
	StubObject string
	// Zig is the resolved zig executable, for the run header.
	Zig string
	// Target is the triple the launcher compiles for, for the run header.
	Target string
}

// zigWindowsTarget picks the windows-gnu triple for this runner's arch. gnu (not
// msvc) is deliberate: zig bundles mingw-w64 + its own libc there, so the
// toolchain is self-contained with nothing installed, and -shared produces a
// PE DLL. The measured Windows leg is amd64; arm64 is handled for completeness.
func zigWindowsTarget() string {
	if runtime.GOARCH == "arm64" {
		return "aarch64-windows-gnu"
	}
	return "x86_64-windows-gnu"
}

// cEscape renders s as the contents of a C string literal: backslashes and
// quotes doubled/escaped. Windows paths are backslash-heavy, and an unescaped
// one would both mangle the path and risk breaking the literal.
func cEscape(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	return s
}

// provisionWindowsFixtureCC puts a working C compiler on the Windows fixture
// PATH the same way bashy provisions every other toolchain: the pinned,
// digest-verified `zig cc` the dag island languages already use (yoke's
// external/zigcc). It compiles a `cc` launcher that targets windows-gnu and
// injects the bundled POSIX fnmatch header, plus a strmatch stub object for the
// loadable link. base is the per-run work directory (parent of the private
// tests tree). It is a no-op off Windows: there the fixtures use the host cc.
func provisionWindowsFixtureCC(base string) (*windowsFixtureCC, error) {
	if runtime.GOOS != "windows" {
		return nil, nil
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
	defer cancel()
	zig, err := zigcc.Ensure(ctx)
	if err != nil {
		return nil, fmt.Errorf("provision zig cc: %w", err)
	}
	dir := filepath.Join(base, "cc")
	compat := filepath.Join(dir, "compat")
	if err := os.MkdirAll(compat, 0o755); err != nil {
		return nil, err
	}
	if err := os.WriteFile(filepath.Join(compat, "fnmatch.h"), fnmatchCompatHeader, 0o644); err != nil {
		return nil, fmt.Errorf("write fnmatch compat header: %w", err)
	}
	target := zigWindowsTarget()

	// Compile the strmatch stub once, for the same target the launcher uses.
	stubObj := filepath.Join(dir, "strmatch_stub.o")
	if err := compileWith(ctx, zig, target, "-c", stubObj, strmatchStubSource, "strmatch_stub.c", ""); err != nil {
		return nil, fmt.Errorf("build strmatch stub: %w", err)
	}

	// Compile the `cc` launcher. Its name is exactly `cc` so the fixture's $CC
	// (which the harness Makefile sets to `cc`) resolves it through PATH/PATHEXT.
	launcherSrc := fmt.Sprintf(ccLauncherSource, cEscape(zig), cEscape(target), cEscape(compat))
	ccExe := filepath.Join(dir, "cc.exe")
	if err := compileWith(ctx, zig, target, "-O2", ccExe, launcherSrc, "cclaunch.c", ""); err != nil {
		return nil, fmt.Errorf("build cc launcher: %w", err)
	}
	return &windowsFixtureCC{Dir: dir, StubObject: stubObj, Zig: zig, Target: target}, nil
}

// compileWith writes src to a temp .c beside out, then runs `zig cc` for target
// to produce out. mode is "-c" (object) or "-O2" (executable). isystem, when
// non-empty, adds a compat include dir. The source file is left in place next
// to the artifact so a failing run can be inspected.
func compileWith(ctx context.Context, zig, target, mode, out, src, name, isystem string) error {
	srcPath := filepath.Join(filepath.Dir(out), name)
	if err := os.WriteFile(srcPath, []byte(src), 0o644); err != nil {
		return err
	}
	args := []string{"cc", "-target", target}
	if isystem != "" {
		args = append(args, "-isystem", isystem)
	}
	args = append(args, mode, "-o", out, srcPath)
	cmd := exec.CommandContext(ctx, zig, args...)
	if outb, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("%w\n%s", err, outb)
	}
	return nil
}

// prependToolsPath puts dir at the front of the fixture PATH (BASH53_TOOLS_PATH,
// a `;`-separated list on Windows) so the provisioned `cc` shadows anything the
// runner might carry. Called before fixturePath is read for the run header.
func prependToolsPath(dir string) {
	existing := strings.TrimSpace(os.Getenv("BASH53_TOOLS_PATH"))
	if existing == "" {
		os.Setenv("BASH53_TOOLS_PATH", dir)
		return
	}
	os.Setenv("BASH53_TOOLS_PATH", dir+";"+existing)
}
