#!/usr/bin/env bash
# dag -> Argo Workflow emitter (compiler-seam prototype, tier 5 / DKS).
#
# Lowers the pinned chunked conformance run (the same corpus property that
# `dag-fanout` distributes across an ssh fleet) into an Argo Workflow that runs
# on k8s / DKS. On k8s the "dynamic hosts" problem the ssh fleet fights by hand
# DISAPPEARS: the k8s scheduler places chunk pods on whatever nodes are up and
# reschedules them off a drained/dead node, and Argo's `retryStrategy` with
# `retryPolicy: OnError` retries SYSTEM failures (pod lost, node gone, OOM-kill)
# WITHOUT retrying a container's non-zero exit — i.e. it retries infra failures
# and keeps test results, exactly the split `dag-fanout` implements manually.
#
# The mapping (dag -> Argo):
#   chunk i (1..N)                 -> a fanned-out pod via `withSequence`
#   aggregate depends on chunks    -> a second step (implicit DAG dependency)
#   FANOUT_RETRY / infra failover  -> retryStrategy{limit, retryPolicy: OnError}
#   resource weights (cpu/mem)     -> container.resources.requests
#   chunks.json chunk_count        -> workflow parameter `chunks` (never derived
#                                     from cluster size — a corpus property)
#
# This emits YAML only. Running it needs: a DKS/k8s cluster with Argo Workflows
# installed, and a SELF-CONTAINED conformance image (testee + harness + fixtures
# baked in — no host mounts on k8s; build it from tools/bash53-container plus the
# linux testee/harness and external/bash-5.3, and push to a registry the cluster
# can pull). See docs/bashpp-dag-tiered-orchestration.md (the compiler seam).
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
IMAGE="${IMAGE:-registry.dks.local/bash53-conformance:latest}"
ARCH="${ARCH:-amd64}"
RETRIES="${RETRIES:-3}"
CPU="${CPU:-1}"; MEM="${MEM:-512Mi}"
NAMESPACE="${NAMESPACE:-conformance}"
PARALLELISM="${PARALLELISM:-0}"   # 0 = unlimited (scheduler decides); else cap concurrent pods
CHUNKS="${CHUNKS:-$(grep -oE '"chunk_count"[: ]*[0-9]+' "$REPO/chunks.json" 2>/dev/null | grep -oE '[0-9]+' | head -1)}"
CHUNKS="${CHUNKS:-8}"
HARNESS="/work/bin/bash53suite-linux-${ARCH}"
TESTEE="/work/bin/bash-linux-${ARCH}/bash"

while [ $# -gt 0 ]; do case "$1" in
  --image) IMAGE="$2"; shift 2;; --arch) ARCH="$2"; shift 2;;
  --retries) RETRIES="$2"; shift 2;; --chunks) CHUNKS="$2"; shift 2;;
  --cpu) CPU="$2"; shift 2;; --mem) MEM="$2"; shift 2;;
  --namespace) NAMESPACE="$2"; shift 2;; --parallelism) PARALLELISM="$2"; shift 2;;
  -h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
  *) echo "unknown flag: $1" >&2; exit 2;;
esac; done

cat <<YAML
# generated by scripts/dag-to-argo.sh — dag chunked conformance -> Argo Workflow
# chunks=${CHUNKS} (pinned in chunks.json) image=${IMAGE} arch=${ARCH} retries=${RETRIES}
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bash53-conformance-
  namespace: ${NAMESPACE}
  labels: { app: bash53-conformance }
spec:
  entrypoint: main
$( [ "$PARALLELISM" != 0 ] && echo "  parallelism: ${PARALLELISM}" )
  # the run is best-effort resilient: a chunk pod lost to a node drain/failure is
  # rescheduled by k8s and retried by Argo; a test FAILURE (container exit != 0
  # WITH output) is NOT an OnError condition, so it is kept, not retried.
  arguments:
    parameters:
      - { name: image,   value: "${IMAGE}" }
      - { name: chunks,  value: "${CHUNKS}" }
      - { name: harness, value: "${HARNESS}" }
      - { name: testee,  value: "${TESTEE}" }
  templates:
    - name: main
      steps:
        - - name: run-chunks
            template: run-chunk
            arguments:
              parameters: [ { name: chunk, value: "{{item}}" } ]
            withSequence: { start: "1", end: "{{workflow.parameters.chunks}}" }
        - - name: aggregate
            template: aggregate
            arguments:
              parameters:
                - name: results
                  value: "{{steps.run-chunks.outputs.parameters.result}}"

    - name: run-chunk
      inputs:
        parameters: [ { name: chunk } ]
      # OnError => retry system/infra errors (pod evicted, node lost, OOM) but
      # NOT a container's non-zero test result. This is the dag-fanout split,
      # native to Argo. backoff spreads retries so a transient cluster event
      # clears before the retry lands.
      retryStrategy:
        limit: "${RETRIES}"
        retryPolicy: "OnError"
        backoff: { duration: "10s", factor: "2", maxDuration: "2m" }
      container:
        image: "{{workflow.parameters.image}}"
        # non-root: the bash-5.3 fixtures that refuse uid 0 (test/new-exp/…) must
        # not run as root (mirror of --user 1000 in the container lane).
        securityContext: { runAsUser: 1000, runAsGroup: 1000 }
        command: [ "sh", "-c" ]
        args:
          - >
            {{workflow.parameters.harness}}
            -tests-dir /bash53/tests
            -chunk {{inputs.parameters.chunk}}/{{workflow.parameters.chunks}}
            -bash {{workflow.parameters.testee}}
            | tee /tmp/out;
            grep -m1 '^Results:' /tmp/out > /tmp/result || echo 'Results: 0 passed, 0 failed' > /tmp/result
        env:
          - { name: BASH53_RUNNER, value: "argo-{{inputs.parameters.chunk}}" }
        resources:
          requests: { cpu: "${CPU}", memory: "${MEM}" }
          limits:   { memory: "4Gi" }
      outputs:
        parameters:
          - name: result
            valueFrom: { path: /tmp/result }

    - name: aggregate
      inputs:
        parameters: [ { name: results } ]   # a JSON array of per-chunk 'Results:' lines
      script:
        image: "{{workflow.parameters.image}}"
        command: [ "sh" ]
        source: |
          # sum passed/failed across all chunk results; fail the workflow only on
          # a real conformance regression (a test FAILED), never on infra.
          printf '%s' '{{inputs.parameters.results}}' \
            | tr -d '[]"' | tr ',' '\n' \
            | awk '/Results:/ { p += \$2; f += \$4 }
                   END { printf "FLEET AGGREGATE: %d passed, %d failed\n", p, f; exit (f>0) }'
YAML
